version: '3'

services:
  web:
    build: ./web
    container_name: chall_catatan_unej
    ports:
      - "8079:5000" 
    networks:
      - ctf-net
    restart: always

  bot:
    build: ./bot
    container_name: chal_catatan_unej
    environment:
      - TARGET_URL=http://web:5000/%252Fnote
      - FLAG=FS26{A51k_k4n_y4_p4k41_b0t_61n14n_21e94y}
    networks:
      - ctf-net
    depends_on:
      - web
    restart: always

networks:
  ctf-net:
    driver: bridge